"""Initial migration

Revision ID: 12429387ae67
Revises: 
Create Date: 2025-09-28 10:09:29.805413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12429387ae67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phone_id', name='unique_user_device')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('outbox_date'))
        batch_op.drop_index(batch_op.f('outbox_sender'))

    with op.batch_alter_table('sentitems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sentitems_date'))
        batch_op.drop_index(batch_op.f('sentitems_dest'))
        batch_op.drop_index(batch_op.f('sentitems_sender'))
        batch_op.drop_index(batch_op.f('sentitems_tpmr'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentitems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sentitems_tpmr'), ['TPMR'], unique=False)
        batch_op.create_index(batch_op.f('sentitems_sender'), ['SenderID'], unique=False)
        batch_op.create_index(batch_op.f('sentitems_dest'), ['DestinationNumber'], unique=False)
        batch_op.create_index(batch_op.f('sentitems_date'), ['DeliveryDateTime'], unique=False)

    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('outbox_sender'), ['SenderID'], unique=False)
        batch_op.create_index(batch_op.f('outbox_date'), ['SendingDateTime', 'SendingTimeOut'], unique=False)

    op.drop_table('user_device')
    op.drop_table('user')
    # ### end Alembic commands ###
